# 这个文件会自动在你git push 项目成功运行 npm install  or npm ci (ci -> 运行.lock相关的版本锁文件)
language: node_js # 使用语言
node_js: # 语言的版本
  - "stable"
cache: # 使用缓存
  directories:
  - node_modules
env: # 环境变量
  - CI=true

# 等待travis CI运行成功，这时候我们需要进行文档部署到travis CI (下面就是自动化部署的配置)
script:
  - npm run build-storybook # 自动运行这个命令，生成静态文件
deploy:
  provider: pages
  skip_cleanup: true
  # 生成的token eccb3cef3c0923f10fb915b30d3461a52d922108
  github_token: $GITHUB_TOKEN 
  local_dir: storybook-static # 上传哪个文件夹的文件
  on:
    branch: master # 哪个branch分支发生变化就执行